# Generated by Django 3.0.4 on 2020-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200326_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='applied_for_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='return_status',
            field=models.CharField(choices=[('initiated', 'INITIATED'), ('requested', 'REQUESTED'), ('completed', 'COMPLETED'), ('NA', 'NA')], default='NA', max_length=100),
        ),
    ]
