# Generated by Django 3.0.4 on 2020-03-28 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order_amount_limit', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LuckyDrawProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated', models.BooleanField(default=False)),
                ('lucky_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_draw_profiles', to='lucky_draw.LuckyDraw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luck_draw_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='luckydraw',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='lucky_draws', through='lucky_draw.LuckyDrawProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='luckydraw',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_lucky_draws', to=settings.AUTH_USER_MODEL),
        ),
    ]
