# Generated by Django 3.0.4 on 2020-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0002_auto_20200328_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydraw',
            name='finished_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
