# Generated by Django 3.0.4 on 2020-03-28 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lucky_draw', '0003_auto_20200328_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydraw',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_lucky_draws', to=settings.AUTH_USER_MODEL),
        ),
    ]
