# Generated by Django 3.0.4 on 2020-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0004_auto_20200328_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydraw',
            name='finished_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
