# Generated by Django 3.0.4 on 2020-03-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200324_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterattribute',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_values', to='products.FilterAttributeName'),
        ),
    ]
