# Generated by Django 3.0.4 on 2020-03-24 13:21

from django.db import migrations, models

import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200324_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_attributes',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='type', chained_model_field='attr__type', horizontal=True, related_name='products', to='products.FilterAttribute'),
        ),
    ]
