# Generated by Django 3.0.4 on 2020-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200324_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex'), ('kid', 'Kid'), ('NA', 'NA')], max_length=50),
        ),
    ]
