# Generated by Django 3.0.4 on 2020-03-24 13:37

from django.db import migrations, models

import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='type',
        ),
        migrations.AddField(
            model_name='productattributename',
            name='type',
            field=models.CharField(blank=True, choices=[('footwear', 'FOOTWEAR'), ('clothing', 'CLOTHING'), ('automobile', 'AUTOMOBILE'), ('furniture', 'FURNITURE'), ('sports-equipment', 'SPORTS-EQUIPMENT'), ('book', 'BOOK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='type', chained_model_field='attr__type', horizontal=True, related_name='products', to='products.ProductAttribute'),
        ),
    ]
