# Generated by Django 3.0.4 on 2020-03-24 13:40

from django.db import migrations

import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200324_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter_attributes',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, horizontal=True, related_name='products', to='products.FilterAttribute'),
        ),
    ]
