# Generated by Django 3.0.4 on 2020-03-24 13:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('products', '0012_auto_20200324_1911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterAttribute',
            new_name='Property',
        ),
        migrations.RenameModel(
            old_name='FilterAttributeName',
            new_name='PropertyName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='filter_attributes',
            new_name='properties',
        ),
    ]
