# Generated by Django 3.0.4 on 2020-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productattributename_view_selection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyname',
            name='view_selection_type',
            field=models.CharField(blank=True, choices=[('single-selection', 'Single Selection'), ('multiple-selection', 'Multiple Selection'), ('NA', 'NA')], max_length=100),
        ),
    ]
