# Generated by Django 3.0.4 on 2020-03-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200325_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='hash',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
